language: python

dist: xenial
# services: xvfb

branches:
  only:
    - master

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

install:
  - pip install cython numpy matplotlib iminuit pytest pytest-mpl
  - pip install flake8 pylint
  # ipython needed for docs: IPython.sphinxext.ipython_directive
  - pip install ipython sphinx sphinx_rtd_theme

script:
  - make build
  - make flake8
  - make pylint
  - make test
  - cd doc && make html
